//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int FlightId { get; set; }
        public string Flight_Nr { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<System.DateTime> ArriveTime { get; set; }
        public Nullable<System.DateTime> ExpectedTime { get; set; }
        public int StatusId { get; set; }
        public int CompanyId { get; set; }
        public string FlightType { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string CreatedByUserId { get; set; }
        public string LastModifiedByUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
