//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementSystem.Models
{
    using AirlineManagementSystem.Enum;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flights
    {
        
        public int FlightId { get; set; }

        [Display(Name = "Flight No.")]
        public string Flight_Nr { get; set; }
        public string From { get; set; }
        public string To { get; set; }

        [Display(Name = "Arrive Time")]
        public Nullable<System.DateTime> ArriveTime { get; set; }

        [Display(Name = "Expected Time")]
        public Nullable<System.DateTime> ExpectedTime { get; set; }

        [Display(Name = "Status")]
        public int StatusId { get; set; }

        [Display(Name = "Company")]
        public int CompanyId { get; set; }

        [Display(Name = "Flight Type")]
        public string FlightType { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public string CreatedByUserId { get; set; }
        public string LastModifiedByUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }

        //public Cities cities { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
